## Default Logstash configuration from logstash-docker.
## from https://github.com/elastic/logstash-docker/blob/master/build/logstash/config/logstash.yml
#
http.host: "0.0.0.0"

# ------------ Pipeline Configuration Settings --------------
#
# Where to fetch the pipeline configuration for the main pipeline
#
path.settings: /usr/share/logstash/pipeline/


# ------------ Data path ------------------
#
# Which directory should be used by logstash and its plugins
# for any persistent needs. Defaults to LOGSTASH_HOME/data
#
path.data: /usr/share/logstash/data/

# ------------ Dead-Letter Queue Settings --------------
# Flag to turn on dead-letter queue.
#
dead_letter_queue.enable: false

## Disable X-Pack
## see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
##     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
#
xpack.monitoring.enabled: false


xpack.monitoring.elasticsearch.url: ${LOGSTASH_ELASTICSEARCH_HOST_ONE}
xpack.monitoring.elasticsearch.username: ${LOGSTASH_ELASTICSEARCH_USER} # Make sure to use this default user for monitoring
xpack.monitoring.elasticsearch.password: ${LOGSTASH_ELASTICSEARCH_PASSWORD}