cluster.name: "elasticsearch-cluster"
network.host: 0.0.0.0

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1
opendistro_security.restapi.roles_enabled:
  ["all_access", "security_rest_api_access"]
opendistro_security.ssl.http.enabled: true
# WARNING: revise all the lines below before you go into production
opendistro_security.ssl.transport.pemcert_filepath: ssl/nodes/elasticsearch.pem
opendistro_security.ssl.transport.pemkey_filepath: ssl/nodes/elasticsearch.key
opendistro_security.ssl.transport.pemtrustedcas_filepath: ssl/root/elasticsearch-rootca.pem
opendistro_security.ssl.transport.enforce_hostname_verification: false
opendistro_security.ssl.http.pemcert_filepath: ssl/nodes/elasticsearch.pem
opendistro_security.ssl.http.pemkey_filepath: ssl/nodes/elasticsearch.key
opendistro_security.ssl.http.pemtrustedcas_filepath: ssl/root/elasticsearch-rootca.pem
opendistro_security.allow_unsafe_democertificates: false
opendistro_security.allow_default_init_securityindex: true

opendistro_security.authcz.admin_dn:
  - CN=kirk,OU=client,O=client,L=test, C=de
  - CN=elasticsearch*,OU=EsClusterOU,O=EsClusterOU,L=Cluj-Napoca,ST=Cluj,C=RO
  - CN=*
opendistro_security.nodes_dn:
  - CN=elasticsearch*,OU=EsClusterOU,O=EsClusterOU,L=Cluj-Napoca,ST=Cluj,C=RO
  - CN=*

http.cors.enabled: true
http.cors.allow-credentials: true
http.cors.allow-origin: "*"
http.cors.allow-headers: X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization, Access-Control-Allow-Headers, Accept


opendistro_security.audit.type: internal_elasticsearch
opendistro_security.enable_snapshot_restore_privilege: true
opendistro_security.check_snapshot_restore_write_privileges: true
opendistro_security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]


cluster.routing.allocation.disk.threshold_enabled: false
node.max_local_storage_nodes: 3
